version: '3.7'
services:
    postgres-db:
      image: postgres:16.2
      ports:
          - '9432:5432'
      volumes:
          - '$HOME/.docker/volumes/pgqueuer_play-db:/var/lib/postgresql/data'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: pgqueuerdb
